name: "CI"
run-name: "Build by - Author: ${{ github.actor }}"

on:
    pull_request:
    push:
        branches:
            - main
        paths:
          - "tests/**"
          - "keepass_yaml_env/**"
          - "poetry.lock"
          - pyproject.toml
          - ".github/**"


jobs:
    static_code_analysis:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Install Poetry
              run: pipx install poetry
            
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
                cache: 'poetry'
            
            - name: Install dependencies
              run: poetry install --with dev
            
            - name: Run linters
              run: |
                poetry run ruff check .
                poetry run black . --check --diff

            
            - name: Run tests
              run: poetry run pytest -v