name: Dependency Security Scan
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    schedule:
        # check every Monday 00:00 for newly discovered CVEs
        - cron: '0 0 * * 1'
jobs:
    scan:
        name: Pip Audit
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Cache requirements.txt
              id: cache-reqs
              uses: actions/cache@v4
              with:
                path: requirements.txt
                key: ${{ runner.os }}-poetry-export-${{ hashFiles('**/poetry.lock') }}
            
            - name: Install poetry
              if: steps.cache-reqs.outputs.cache-hit != 'true'
              run: pipx install poetry
            
            - name: Export poetry dependencies into requirements.txt
              if: steps.cache-reqs.outputs.cache-hit != 'true'
              run: poetry export -f requirements.txt --output requirements.txt --without-hashes

            - name: Run pip-audit
              uses: pypa/gh-action-pip-audit@v1.1.0
              with:
                inputs: requirements.txt