name: Publish to PyPI
run-name: "Published to PyPI by - Author: ${{ github.actor }}"

on:
  workflow_dispatch:
    inputs:
      publish_test:
        description: "Is this publishing only a test to test.pypi.org?"
        required: false
        default: true
        type: boolean

  release:
    types: [published]

jobs:
  pypi-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    
    environment:
      name: pypi
      url: https://pypi.org/p/keepass_yaml_env
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pipx install poetry

      - name: Build project
        run: poetry build

    #   [TEST PYPI DISTRIBUTION]
      - name: Publish package distributions to TestPyPI
        if: ${{ inputs.publish_test }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
    
    #   [PUBLIC DISTRIBUTION]
      - name: Publish package distributions to PyPI
        if: ${{ ! inputs.publish_test }}
        uses: pypa/gh-action-pypi-publish@release/v1